<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Select_Entitiy IP Power Table</name>
   <tag></tag>
   <elementGuidId>2a78e2ad-3f34-450d-b3bd-c55ff7c2d4d8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#select-options-RequestHeader_EntityIPOwnerNew</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='select-options-RequestHeader_EntityIPOwnerNew']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>ul</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select-options-RequestHeader_EntityIPOwnerNew</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-content select-dropdown w-100 active</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Choose your option     Innogene Kalbiotech PTE. LTD.     Kalbe International PTE. LTD - Sri Lanka Liaison Office     Kalbe International PTE. LTD.     Kalbe International PTE. LTD. (Yangon Branch)     Kalbe International PTE. LTD. - South Africa Branch     Kalbe International PTE. LTD. Philippines Rep. Office     Kalbe Lanka PVT. LTD.     Kalbe Malaysia SDN. BHD.     Kalbe Myanmar CO. LTD.     Kalbe Vision PTE. LTD.     Orange Kalbe Limited     PT. Agroveta Husada Dharma     PT. Bifarma Adiluhung     PT. Bintang Toedjoe     PT. Cakra Radha Mustika     PT. Dankos Farma     PT. Emos Global Digital     PT. Enseval Medika Prima     PT. Enseval Putera Megatrading, Tbk     PT. Finusolprima Farma Internasional     PT. Forsta Kalmedic Global     PT. Global Chemindo Megatrading     PT. Global Karsa Medika     PT. Global Onkolab Farma     PT. Global Vita Nutritech     PT. Hale International     PT. Hexpharm Jaya Laboratories     PT. Innolab Sains Internasional     PT. Kalbe Biotek Indonesia     PT. Kalbe Blackmores Nutritions     PT. Kalbe Farma Tbk.     PT. Kalbe Genexine Biologics     PT. Kalbe Milko Indonesia     PT. Kalbe Morinaga Indonesia     PT. Kalbio Global Medika     PT. Kalgen DNA     PT. Karsa Lintas Buwana     PT. Karya Hasta Dinamika     PT. Medika Komunika Teknologi     PT. Medika Renal Citraprima     PT. Millenia Dharma Insani     PT. Pharma Metric Labs     PT. Renalmed Tiara Utama     PT. Saka Farma Laboratories     PT. Sanghiang Perkasa     PT. Tri Sapta Jaya     Unit Test    </value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select-options-RequestHeader_EntityIPOwnerNew&quot;)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//ul[@id='select-options-RequestHeader_EntityIPOwnerNew']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='newEntityIPOwner']/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/ul</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='▼'])[1]/following::ul[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Entity IP Owner'])[1]/following::ul[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/ul</value>
   </webElementXpaths>
</WebElementEntity>
