<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_select_dropDown_EntityIPOwner</name>
   <tag></tag>
   <elementGuidId>eadf3f4e-40b4-4d7a-a1da-9348a2a7ac6e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@value=''])[6]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.select-dropdown.form-control.valid</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select-dropdown form-control valid</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>readonly</name>
      <type>Main</type>
      <value>true</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>false</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-activates</name>
      <type>Main</type>
      <value>select-options-RequestHeader_EntityIPOwnerNew</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>combobox</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-multiselectable</name>
      <type>Main</type>
      <value>false</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>false</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>true</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>-error -error -error -error -error -error -error -error -error -error -error -error -error -error -error -error -error</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;newEntityIPOwner&quot;)/div[@class=&quot;cls-kalbe select-outline&quot;]/div[@class=&quot;select-wrapper mdb-select md-form md-outline colorful-select dropdown-primary&quot;]/div[@class=&quot;select-wrapper mdb-select md-form md-outline colorful-select dropdown-primary&quot;]/div[@class=&quot;select-wrapper mdb-select md-form md-outline colorful-select dropdown-primary&quot;]/div[@class=&quot;select-wrapper mdb-select md-form md-outline colorful-select dropdown-primary&quot;]/div[@class=&quot;select-wrapper mdb-select md-form md-outline colorful-select dropdown-primary&quot;]/div[@class=&quot;select-wrapper mdb-select md-form md-outline colorful-select dropdown-primary&quot;]/div[@class=&quot;select-wrapper mdb-select md-form md-outline colorful-select dropdown-primary&quot;]/div[@class=&quot;select-wrapper mdb-select md-form md-outline colorful-select dropdown-primary&quot;]/div[@class=&quot;select-wrapper mdb-select md-form md-outline colorful-select dropdown-primary&quot;]/div[@class=&quot;select-wrapper mdb-select md-form md-outline colorful-select dropdown-primary&quot;]/div[@class=&quot;select-wrapper mdb-select md-form md-outline colorful-select dropdown-primary&quot;]/div[@class=&quot;select-wrapper mdb-select md-form md-outline colorful-select dropdown-primary&quot;]/div[@class=&quot;select-wrapper mdb-select md-form md-outline colorful-select dropdown-primary&quot;]/div[@class=&quot;select-wrapper mdb-select md-form md-outline colorful-select dropdown-primary&quot;]/div[@class=&quot;select-wrapper mdb-select md-form md-outline colorful-select dropdown-primary&quot;]/div[@class=&quot;select-wrapper mdb-select md-form md-outline colorful-select dropdown-primary&quot;]/div[@class=&quot;select-wrapper mdb-select md-form md-outline colorful-select dropdown-primary&quot;]/div[@class=&quot;select-wrapper mdb-select md-form md-outline colorful-select dropdown-primary&quot;]/div[@class=&quot;select-wrapper mdb-select md-form md-outline colorful-select dropdown-primary&quot;]/div[@class=&quot;select-wrapper mdb-select md-form md-outline colorful-select dropdown-primary&quot;]/div[@class=&quot;select-wrapper mdb-select md-form md-outline colorful-select dropdown-primary&quot;]/div[@class=&quot;select-wrapper mdb-select md-form md-outline colorful-select dropdown-primary&quot;]/div[@class=&quot;select-wrapper mdb-select md-form md-outline colorful-select dropdown-primary&quot;]/div[@class=&quot;select-wrapper mdb-select md-form md-outline colorful-select dropdown-primary&quot;]/div[@class=&quot;select-wrapper mdb-select md-form md-outline colorful-select dropdown-primary&quot;]/div[@class=&quot;select-wrapper mdb-select md-form md-outline colorful-select dropdown-primary&quot;]/div[@class=&quot;select-wrapper mdb-select md-form md-outline colorful-select dropdown-primary&quot;]/div[@class=&quot;select-wrapper mdb-select md-form md-outline colorful-select dropdown-primary&quot;]/div[@class=&quot;select-wrapper mdb-select md-form md-outline colorful-select dropdown-primary&quot;]/div[@class=&quot;select-wrapper mdb-select md-form md-outline colorful-select dropdown-primary&quot;]/div[@class=&quot;select-wrapper mdb-select md-form md-outline colorful-select dropdown-primary&quot;]/div[@class=&quot;select-wrapper mdb-select md-form md-outline colorful-select dropdown-primary&quot;]/div[@class=&quot;select-wrapper mdb-select md-form md-outline colorful-select dropdown-primary&quot;]/div[@class=&quot;select-wrapper mdb-select md-form md-outline colorful-select dropdown-primary&quot;]/div[@class=&quot;select-wrapper mdb-select md-form md-outline colorful-select dropdown-primary&quot;]/div[@class=&quot;select-wrapper mdb-select md-form md-outline colorful-select dropdown-primary&quot;]/div[@class=&quot;select-wrapper mdb-select md-form md-outline colorful-select dropdown-primary&quot;]/div[@class=&quot;select-wrapper mdb-select md-form md-outline colorful-select dropdown-primary&quot;]/div[@class=&quot;select-wrapper mdb-select md-form md-outline colorful-select dropdown-primary&quot;]/div[@class=&quot;select-wrapper mdb-select md-form md-outline colorful-select dropdown-primary&quot;]/div[@class=&quot;select-wrapper mdb-select md-form md-outline colorful-select dropdown-primary&quot;]/div[@class=&quot;select-wrapper mdb-select md-form md-outline colorful-select dropdown-primary&quot;]/div[@class=&quot;select-wrapper mdb-select md-form md-outline colorful-select dropdown-primary&quot;]/div[@class=&quot;select-wrapper mdb-select md-form md-outline colorful-select dropdown-primary&quot;]/div[@class=&quot;select-wrapper mdb-select md-form md-outline colorful-select dropdown-primary&quot;]/div[@class=&quot;select-wrapper mdb-select md-form md-outline colorful-select dropdown-primary&quot;]/div[@class=&quot;select-wrapper mdb-select md-form md-outline colorful-select dropdown-primary&quot;]/div[@class=&quot;select-wrapper mdb-select md-form md-outline colorful-select dropdown-primary&quot;]/div[@class=&quot;select-wrapper mdb-select md-form md-outline colorful-select dropdown-primary&quot;]/div[@class=&quot;select-wrapper mdb-select md-form md-outline colorful-select dropdown-primary&quot;]/input[@class=&quot;select-dropdown form-control valid&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@value=''])[6]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='newEntityIPOwner']/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div/div/div/div/div/input</value>
   </webElementXpaths>
</WebElementEntity>
