<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Checkbox_Auto Renewal</name>
   <tag></tag>
   <elementGuidId>c71cbe1a-edf8-49a1-9f6e-d80bb2343b75</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#frmSalesAgreement > div.row.pb-2.div-section > div.col-md-3.old > div.cls-kalbe > div.input-group > div.input-group-append.pb-2.check-new > label.form-check-label</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='frmSalesAgreement']/div[4]/div/div/div/div/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-label</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>SalesAgreement_CheckNewAutoRenewal</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmSalesAgreement&quot;)/div[@class=&quot;row  pb-2 div-section&quot;]/div[@class=&quot;col-md-3 old&quot;]/div[@class=&quot;cls-kalbe&quot;]/div[@class=&quot;input-group&quot;]/div[@class=&quot;input-group-append pb-2 check-new&quot;]/label[@class=&quot;form-check-label&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmSalesAgreement']/div[4]/div/div/div/div/label</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form[8]/div[4]/div/div/div/div/label</value>
   </webElementXpaths>
</WebElementEntity>
