<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Choose your option                AE_449152</name>
   <tag></tag>
   <elementGuidId>988c49a2-ed4b-4230-a493-3b9c65daedcc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='DisputeHeader_CurrencyNew']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#DisputeHeader_CurrencyNew</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mdb-select md-form md-outline colorful-select dropdown-primary input-requestor amountOfDebt initialized</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>searchable</name>
      <type>Main</type>
      <value>Search here..</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>DisputeHeader_CurrencyNew</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>DisputeHeader.CurrencyNew</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-stop-refresh</name>
      <type>Main</type>
      <value>true</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                    Choose your option
                AED - United Arab Emirates dirhamAFN - Afghan afghaniALL - Albanian lekAMD - Armenian dramANG - Netherlands Antillean guilderAOA - Angolan kwanzaARS - Argentine pesoAUD - Australian dollarAWG - Aruban florinAZN - Azerbaijani manatBAM - Bosnia and Herzegovina convertible markBBD - Barbados dollarBDT - Bangladeshi takaBGN - Bulgarian levBHD - Bahraini dinarBIF - Burundian francBMD - Bermudian dollarBND - Brunei dollarBOB - BolivianoBRL - Brazilian realBSD - Bahamian dollarBTN - Bhutanese ngultrumBWP - Botswana pulaBYN - Belarusian rubleBZD - Belize dollarCAD - Canadian dollarCDF - Congolese francCHF - Swiss francCLP - Chilean pesoCNY - Chinese yuan[8]COP - Colombian pesoCRC - Costa Rican colonCUP - Cuban pesoCVE - Cape Verdean escudoCZK - Czech korunaDJF - Djiboutian francDKK - Danish kroneDOP - Dominican pesoDZD - Algerian dinarEGP - Egyptian poundERN - Eritrean nakfaETB - Ethiopian birrEUR - EuroFJD - Fiji dollarFKP - Falkland Islands poundGBP - Pound sterlingGEL - Georgian lariGHS - Ghanaian cediGIP - Gibraltar poundGMD - Gambian dalasiGNF - Guinean francGTQ - Guatemalan quetzalGYD - Guyanese dollarHKD - Hong Kong dollarHNL - Honduran lempiraHRK - Croatian kunaHTG - Haitian gourdeHUF - Hungarian forintIDR - Indonesian rupiahILS - Israeli new shekelINR - Indian rupeeIQD - Iraqi dinarIRR - Iranian rialISK - Icelandic krónaJMD - Jamaican dollarJOD - Jordanian dinarJPY - Japanese yenKES - Kenyan shillingKGS - Kyrgyzstani somKHR - Cambodian rielKMF - Comoro francKPW - North Korean wonKRW - South Korean wonKWD - Kuwaiti dinarKYD - Cayman Islands dollarKZT - Kazakhstani tengeLAK - Lao kipLBP - Lebanese poundLKR - Sri Lankan rupeeLRD - Liberian dollarLSL - Lesotho lotiLYD - Libyan dinarMAD - Moroccan dirhamMDL - Moldovan leuMGA - Malagasy ariaryMKD - Macedonian denarMMK - Myanmar kyatMNT - Mongolian tögrögMOP - Macanese patacaMRU - Mauritanian ouguiyaMUR - Mauritian rupeeMVR - Maldivian rufiyaaMWK - Malawian kwachaMXN - Mexican pesoMYR - Malaysian ringgitMZN - Mozambican meticalNAD - Namibian dollarNGN - Nigerian nairaNIO - Nicaraguan córdobaNOK - Norwegian kroneNPR - Nepalese rupeeNZD - New Zealand dollarOMR - Omani rialPAB - Panamanian balboaPEN - Peruvian solPGK - Papua New Guinean kinaPHP - Philippine pesoPKR - Pakistani rupeePLN - Polish zlotyPYG - Paraguayan guaraníQAR - Qatari riyalRON - Romanian leuRSD - Serbian dinarRUB - Russian rubleRWF - Rwandan francSAR - Saudi riyalSBD - Solomon Islands dollarSCR - Seychelles rupeeSDG - Sudanese poundSEK - Swedish krona/kronorSGD - Singapore dollarSHP - Saint Helena poundSLL - Sierra Leonean leoneSOS - Somali shillingSRD - Surinamese dollarSSP - South Sudanese poundSTN - São Tomé and Príncipe dobraSVC - Salvadoran colónSYP - Syrian poundSZL - Swazi lilangeniTHB - Thai bahtTJS - Tajikistani somoniTMT - Turkmenistan manatTND - Tunisian dinarTOP - Tongan pa?angaTRY - Turkish liraTTD - Trinidad and Tobago dollarTWD - New Taiwan dollarTZS - Tanzanian shillingUAH - Ukrainian hryvniaUGX - Ugandan shillingUSD - United States dollarUYU - Uruguayan pesoUZS - Uzbekistan somVES - Venezuelan bolívar soberanoVND - Vietnamese d?ngVUV - Vanuatu vatuWST - Samoan talaXAF - CFA franc BEACXCD - East Caribbean dollarXOF - CFA franc BCEAOXPF - CFP franc (NEWID(),franc Pacifique)YER - Yemeni rialZAR - South African randZMW - Zambian kwachaZWL - Zimbabwean dollar</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DisputeHeader_CurrencyNew&quot;)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='DisputeHeader_CurrencyNew']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmDetailCounterpart']/div[4]/div[2]/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/select</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ZWL - Zimbabwean dollar'])[1]/following::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ZMW - Zambian kwacha'])[1]/following::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Amount'])[1]/preceding::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='International Company'])[1]/preceding::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/select</value>
   </webElementXpaths>
</WebElementEntity>
