<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__select_Territory_PATENT</name>
   <tag></tag>
   <elementGuidId>3aa59fb8-0996-48da-bafc-e80ea0177cf9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.cls-kalbe.select-outline > div.select-wrapper.mdb-select.md-form.md-outline.colorful-select.dropdown-primary.input-requestor > div.select-wrapper.mdb-select.md-form.md-outline.colorful-select.dropdown-primary.input-requestor > div.select-wrapper.mdb-select.md-form.md-outline.colorful-select.dropdown-primary.input-requestor > div.select-wrapper.mdb-select.md-form.md-outline.colorful-select.dropdown-primary.input-requestor > div.select-wrapper.mdb-select.md-form.md-outline.colorful-select.dropdown-primary.input-requestor > input.select-dropdown.form-control</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@value=''])[24]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select-dropdown form-control</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>readonly</name>
      <type>Main</type>
      <value>true</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>false</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-activates</name>
      <type>Main</type>
      <value>select-options-PatentDetail_TerritoryNew</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>combobox</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-multiselectable</name>
      <type>Main</type>
      <value>false</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>true</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmDetailPatent&quot;)/div[@class=&quot;row pb-3 div-section&quot;]/div[@class=&quot;col-md-6 new&quot;]/div[@class=&quot;cls-kalbe select-outline&quot;]/div[@class=&quot;select-wrapper mdb-select md-form md-outline colorful-select dropdown-primary input-requestor&quot;]/div[@class=&quot;select-wrapper mdb-select md-form md-outline colorful-select dropdown-primary input-requestor&quot;]/div[@class=&quot;select-wrapper mdb-select md-form md-outline colorful-select dropdown-primary input-requestor&quot;]/div[@class=&quot;select-wrapper mdb-select md-form md-outline colorful-select dropdown-primary input-requestor&quot;]/div[@class=&quot;select-wrapper mdb-select md-form md-outline colorful-select dropdown-primary input-requestor&quot;]/input[@class=&quot;select-dropdown form-control&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@value=''])[24]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmDetailPatent']/div[8]/div[2]/div/div/div/div/div/div/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/div/input</value>
   </webElementXpaths>
</WebElementEntity>
