<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__select-dropdown form-control</name>
   <tag></tag>
   <elementGuidId>01b0fad9-ac40-48ac-a148-98621a9a198d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.select-dropdown.form-control</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@value=''])[8]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select-dropdown form-control</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>readonly</name>
      <type>Main</type>
      <value>true</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>false</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-activates</name>
      <type>Main</type>
      <value>select-options-RequestHeaderDocsLetter_EntityInDocsLetterNew</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>combobox</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-multiselectable</name>
      <type>Main</type>
      <value>false</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>true</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;newEntityDocsLetter&quot;)/div[@class=&quot;cls-kalbe&quot;]/div[@class=&quot;select-wrapper mdb-select md-form md-outline colorful-select dropdown-success input-requestor&quot;]/div[@class=&quot;select-wrapper mdb-select md-form md-outline colorful-select dropdown-success input-requestor&quot;]/div[@class=&quot;select-wrapper mdb-select md-form md-outline colorful-select dropdown-success input-requestor&quot;]/div[@class=&quot;select-wrapper mdb-select md-form md-outline colorful-select dropdown-success input-requestor&quot;]/div[@class=&quot;select-wrapper mdb-select md-form md-outline colorful-select dropdown-success input-requestor&quot;]/div[@class=&quot;select-wrapper mdb-select md-form md-outline colorful-select dropdown-success input-requestor&quot;]/div[@class=&quot;select-wrapper mdb-select md-form md-outline colorful-select dropdown-success input-requestor&quot;]/div[@class=&quot;select-wrapper mdb-select md-form md-outline colorful-select dropdown-success input-requestor&quot;]/div[@class=&quot;select-wrapper mdb-select md-form md-outline colorful-select dropdown-success input-requestor&quot;]/div[@class=&quot;select-wrapper mdb-select md-form md-outline colorful-select dropdown-success input-requestor&quot;]/div[@class=&quot;select-wrapper mdb-select md-form md-outline colorful-select dropdown-success input-requestor&quot;]/div[@class=&quot;select-wrapper mdb-select md-form md-outline colorful-select dropdown-success input-requestor&quot;]/div[@class=&quot;select-wrapper mdb-select md-form md-outline colorful-select dropdown-success input-requestor&quot;]/div[@class=&quot;select-wrapper mdb-select md-form md-outline colorful-select dropdown-success input-requestor&quot;]/div[@class=&quot;select-wrapper mdb-select md-form md-outline colorful-select dropdown-success input-requestor&quot;]/div[@class=&quot;select-wrapper mdb-select md-form md-outline colorful-select dropdown-success input-requestor&quot;]/div[@class=&quot;select-wrapper mdb-select md-form md-outline colorful-select dropdown-success input-requestor&quot;]/div[@class=&quot;select-wrapper mdb-select md-form md-outline colorful-select dropdown-success input-requestor&quot;]/div[@class=&quot;select-wrapper mdb-select md-form md-outline colorful-select dropdown-success input-requestor&quot;]/div[@class=&quot;select-wrapper mdb-select md-form md-outline colorful-select dropdown-success input-requestor&quot;]/div[@class=&quot;select-wrapper mdb-select md-form md-outline colorful-select dropdown-success input-requestor&quot;]/div[@class=&quot;select-wrapper mdb-select md-form md-outline colorful-select dropdown-success input-requestor&quot;]/div[@class=&quot;select-wrapper mdb-select md-form md-outline colorful-select dropdown-success input-requestor&quot;]/div[@class=&quot;select-wrapper mdb-select md-form md-outline colorful-select dropdown-success input-requestor&quot;]/div[@class=&quot;select-wrapper mdb-select md-form md-outline colorful-select dropdown-success input-requestor&quot;]/div[@class=&quot;select-wrapper mdb-select md-form md-outline colorful-select dropdown-success input-requestor&quot;]/div[@class=&quot;select-wrapper mdb-select md-form md-outline colorful-select dropdown-success input-requestor&quot;]/div[@class=&quot;select-wrapper mdb-select md-form md-outline colorful-select dropdown-success input-requestor&quot;]/div[@class=&quot;select-wrapper mdb-select md-form md-outline colorful-select dropdown-success input-requestor&quot;]/div[@class=&quot;select-wrapper mdb-select md-form md-outline colorful-select dropdown-success input-requestor&quot;]/div[@class=&quot;select-wrapper mdb-select md-form md-outline colorful-select dropdown-success input-requestor&quot;]/div[@class=&quot;select-wrapper mdb-select md-form md-outline colorful-select dropdown-success input-requestor&quot;]/div[@class=&quot;select-wrapper mdb-select md-form md-outline colorful-select dropdown-success input-requestor&quot;]/div[@class=&quot;select-wrapper mdb-select md-form md-outline colorful-select dropdown-success input-requestor&quot;]/div[@class=&quot;select-wrapper mdb-select md-form md-outline colorful-select dropdown-success input-requestor&quot;]/div[@class=&quot;select-wrapper mdb-select md-form md-outline colorful-select dropdown-success input-requestor&quot;]/div[@class=&quot;select-wrapper mdb-select md-form md-outline colorful-select dropdown-success input-requestor&quot;]/div[@class=&quot;select-wrapper mdb-select md-form md-outline colorful-select dropdown-success input-requestor&quot;]/div[@class=&quot;select-wrapper mdb-select md-form md-outline colorful-select dropdown-success input-requestor&quot;]/div[@class=&quot;select-wrapper mdb-select md-form md-outline colorful-select dropdown-success input-requestor&quot;]/div[@class=&quot;select-wrapper mdb-select md-form md-outline colorful-select dropdown-success input-requestor&quot;]/div[@class=&quot;select-wrapper mdb-select md-form md-outline colorful-select dropdown-success input-requestor&quot;]/div[@class=&quot;select-wrapper mdb-select md-form md-outline colorful-select dropdown-success input-requestor&quot;]/div[@class=&quot;select-wrapper mdb-select md-form md-outline colorful-select dropdown-success input-requestor&quot;]/div[@class=&quot;select-wrapper mdb-select md-form md-outline colorful-select dropdown-success input-requestor&quot;]/div[@class=&quot;select-wrapper mdb-select md-form md-outline colorful-select dropdown-success input-requestor&quot;]/div[@class=&quot;select-wrapper mdb-select md-form md-outline colorful-select dropdown-success input-requestor&quot;]/div[@class=&quot;select-wrapper mdb-select md-form md-outline colorful-select dropdown-success input-requestor active&quot;]/input[@class=&quot;select-dropdown form-control&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@value=''])[8]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='newEntityDocsLetter']/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div/div/div/div/div/input</value>
   </webElementXpaths>
</WebElementEntity>
