<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_EntityAgreement</name>
   <tag></tag>
   <elementGuidId>c543e84d-0257-481a-90cf-f516f8d46ce0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='RequestHeader_EntityInAgreementNew']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#RequestHeader_EntityInAgreementNew</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control texts input-requestor valid</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>This field is required.</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>RequestHeader_EntityInAgreementNew</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>RequestHeader.EntityInAgreementNew</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>RequestHeader_EntityInAgreementNew-error</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                        Choose your option
                    Innogene Kalbiotech PTE. LTD.Kalbe International PTE. LTD - Sri Lanka Liaison OfficeKalbe International PTE. LTD.Kalbe International PTE. LTD. - South Africa BranchKalbe International PTE. LTD. (Yangon Branch)Kalbe International PTE. LTD. Philippines Rep. OfficeKalbe Lanka PVT. LTD.Kalbe Malaysia SDN. BHD.Kalbe Myanmar CO. LTD.Kalbe Vision PTE. LTD.Orange Kalbe LimitedPT. Agroveta Husada DharmaPT. Bifarma AdiluhungPT. Bintang ToedjoePT. Cakra Radha MustikaPT. Dankos FarmaPT. Emos Global DigitalPT. Enseval Medika PrimaPT. Enseval Putera Megatrading, TbkPT. Finusolprima Farma InternasionalPT. Forsta Kalmedic GlobalPT. Global Chemindo MegatradingPT. Global Karsa MedikaPT. Global Onkolab FarmaPT. Global Vita NutritechPT. Hale InternationalPT. Hexpharm Jaya LaboratoriesPT. Innolab Sains InternasionalPT. Kalbe Biotek IndonesiaPT. Kalbe Blackmores NutritionsPT. Kalbe Farma Tbk.PT. Kalbe Genexine BiologicsPT. Kalbe Milko IndonesiaPT. Kalbe Morinaga IndonesiaPT. Kalbio Global MedikaPT. Kalgen DNAPT. Karsa Lintas BuwanaPT. Karya Hasta DinamikaPT. Medika Komunika TeknologiPT. Medika Renal CitraprimaPT. Millenia Dharma InsaniPT. Pharma Metric LabsPT. Renalmed Tiara UtamaPT. Saka Farma LaboratoriesPT. Sanghiang PerkasaPT. Tri Sapta Jaya</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;RequestHeader_EntityInAgreementNew&quot;)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='RequestHeader_EntityInAgreementNew']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='newEntityAgreement']/div/select</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Entity In Agreement'])[1]/following::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Notes'])[1]/following::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Request No.'])[1]/preceding::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Requestor'])[1]/preceding::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div/select</value>
   </webElementXpaths>
</WebElementEntity>
